### ISSUE TITLE
canvasの大きさ

### ISSUE THREAD

**Issue by TetsuakiBaba** [miyazaki-yuko/syuryoImageGenerator#4]
微妙にcanvasの大きさが右側はみ出ちゃってるね．ピッタリしてほしいつもりでした．#issueの練習

**Comment by miyazaki-yuko** [comment]
widthをcontainerじゃなくてcanvasから取ってきたらまずいです？

**Comment by TetsuakiBaba** [comment]
containerの横幅をcanvasに適応させてるつもりです．

**Comment by miyazaki-yuko** [comment]
なぜはみ出すのか…

**Comment by TetsuakiBaba** [comment]
なぞだよね．おれも見つけたら治して報告するぜ．

**Comment by TetsuakiBaba** [comment]
解決しました．
[9612bd4](https://github.com/miyazaki-yuko/syuryoImageGenerator/pull/7/commits/9612bd4373c09e045c263a1746c7c486d99af7e4)
